server {
    listen 80;
    server_name _;

    # Laravel API
    location /api {
        alias /var/www/laravel/public;
        try_files $uri $uri/ @laravel_api;
        
        location ~ \.php$ {
            fastcgi_pass php84:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;
            include fastcgi_params;
        }
    }

    location @laravel_api {
        rewrite /api/(.*)$ /api/index.php?/$1 last;
    }

    # Laravel Security
    location / {
        root /var/www/security/public;
        index index.php;
        try_files $uri $uri/ /index.php?$query_string;
        
        location ~ \.php$ {
            fastcgi_pass php84:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
