opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.revalidate_freq=2
opcache.fast_shutdown=1
memory_limit=256M
realpath_cache_size=4096K
realpath_cache_ttl=600

; Logs - Monolítico
error_log = /var/log/php/monolitico-error.log
log_errors = On
error_reporting = E_ALL
display_errors = Off
